# Generated by Django 4.2.4 on 2023-08-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rent", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rental",
            name="car_price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
