# Generated by Django 4.2.4 on 2023-09-01 09:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rent", "0002_rental_car_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rental",
            old_name="car_price",
            new_name="total_price",
        ),
    ]
